splunk-quarkus/README.md, splunk-quarkus/devel.json
Adds `ACG_CONFIG` to the dev run and updates `devel.json`.
=> docs: Update dev running step and dev config

splunk-quarkus/ephemeral_build_image.sh, splunk-quarkus/init_ephemeral_cluster.sh
Adding init_ephemeral_cluster script so we can easily deploy the resources to ephemeral
=> [EVNT-189] Add init_ephemeral_cluster and ephemeral_build_image scripts 

splunk-quarkus/pr_check.sh
=> build: fix build of image and pr_check

notifications-helpers/create_application_full.py, splunk-quarkus/README.md, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Migrate to using secret_token out of metadata as a Slunk token.
=> [EVNT-169] feat: use secret_token value

splunk-quarkus/clowdapp.yaml
=> [EVNT-242] chore(clowder): add notifications-backend as dependency

splunk-quarkus/pr_check.sh
=> [EVNT-245] Enable smoke test

splunk-quarkus/clowdapp.yaml
This PR changes the deploymentStrategy of our service.
=> [EVNT-237] Change Clowdapp deploymentStrategy

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Update error log message to be clear and easy to understand.
=> [EVNT-354] Update logged error message

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/EventAppender.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
- [EVNT-327] Changes simple bean to full fledged aggregator
- [EVNT-327] Aggregate by metadata header
=> [EVNT-327] Proper aggregation of messages

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Reverts RedHatInsights/eventing-integrations#42
=> Revert "[EVNT-389] Reorder handlers, errors first"

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Reverts RedHatInsights/eventing-integrations#41
=> Revert "[EVNT-383] Add http exception handling"

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Adds exception handler for `org.apache.camel.http.common.HttpOperationFailedException`
with additional logging.
=> [EVNT-374] Add onException for HTTP

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Reverts RedHatInsights/eventing-integrations#46
=> [EVNT-411] Revert "[EVNT-410] Add token to error log"

eclipse-formatter-config.xml, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/CloudEventDecoder.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/CloudEventEncoder.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/EventPicker.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/ResultTransformer.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Run code through formatter:
```
../mvnw formatter:format
```
=> refactor: update formatter config and re-format code

grafana/grafana-dashboard-insights-eventing-general.configmap.yaml
Fixes the threshold coloring for Success Rate counter.
EVNT-259
=> fix(grafana): update threshold colors for success rate

README.md
=> docs: add process for updating dependencies

splunk-quarkus/Dockerfile.jvm, splunk-quarkus/README.md
=> build: silence progress output during build

splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/TargetUrlValidator.java, splunk-quarkus/src/test/java/com/redhat/console/notifications/splunkintegration/TargetUrlValidatorTest.java
test: modifies unit tests for TargetUrlValidator
EVNT-261
Co-authored-by: Joao Paulo Ramos <jramos@redhat.com>
=> feat: rejects http protocol

splunk-quarkus/devel.json, splunk-quarkus/pom.xml
This adds fixes for Clowder's appinferface logging provider.
EVNT-171
=> chore(deps): bump clowder-quarkus-config-source

splunk-quarkus/src/main/resources/application.properties
=> chore(logging): set INFO log level for cloudwatch

splunk-quarkus/README.md, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/CloudEventDecoder.java, splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Parse and expose `orgId` for log messages.
EVNT-559
=> [EVNT-559] feat: log orgId in messages

grafana/grafana-dashboard-insights-eventing-general.configmap.yaml
Adds Handling Success (SLO) value and graph.
Added secure failure counter and rate.
Added URL validation failure rate.
Updates titles and positioning.
EVNT-606
=> feat(grafana): add handling sucess (SLO)

splunk-quarkus/src/main/java/com/redhat/console/integrations/MainRoutes.java
=> clean(route): drop temp logging

build_deploy.sh
This should smooth out the transition to new Quay repo.
EVNT-613
=> ci: build old image until full migration

pr_check.sh
for smoother migration
EVNT-613
=> ci: push to old image during pr-check

clowdapp.yaml, splunk-quarkus/Dockerfile.jvm
Adds INTEGRATION_HANDLER_PATTERN and INTEGRATION_COMPONENT_NAME env
vars into Dockerfile that would control type of integration.
Creates a root clowdapp. The Splunk one would eventually migrato to the root ClowdApp named
eventing-integrations.
EVNT-642 EVNT-609
=> feat(clowdapp): servicenow deployment ClowdApp

splunk-quarkus/src/main/resources/application.properties
Use `integrations.component.name` property on other important
applications properties that control different types of integrations.
EVNT-642
=> feat: component aware props values

clowdapp.yaml, splunk-quarkus/Dockerfile.jvm, splunk-quarkus/clowdapp.yaml, splunk-quarkus/src/main/java/com/redhat/console/integrations/MainRoutes.java, splunk-quarkus/src/main/resources/application.properties
feat(kafka): read kafka topic names from clowder config
[EVNT-448]
=> Allows to use kafka topic names from clowder

splunk-quarkus/pom.xml, splunk-quarkus/src/main/java/com/redhat/console/integrations/servicenow/ServiceNowIntegration.java, splunk-quarkus/src/main/java/com/redhat/console/integrations/splunk/SplunkIntegration.java
Use parallel processing for aggregator in Splunk integration, and async SEDA queue with concurrent consumers for SNOW integration.
EVNT-791
=> feat: parallel processing

splunk-quarkus/pom.xml
=> chore: update Quarkus to 2.16.1.Final

pr_check.sh
- Prevents resource limitation on dependant services system-baseline and historical-system-profiles services
=> fix(ci): adjust resources for dependencies

splunk-quarkus/pom.xml, splunk-quarkus/src/test/java/com/redhat/console/integrations/CloudEventDecoderTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/testhelpers/CloudEventTestHelper.java, splunk-quarkus/src/test/resources/application.properties
The goal is to get notified if we change anything from the decoder.
=> feature: tests for the cloud event decoder

splunk-quarkus/clowdapp.yaml
=> chore(k8s): lower CPU k8s resources

.gitignore, splunk-quarkus/pom.xml, splunk-quarkus/src/test/java/com/redhat/console/integrations/CloudEventDecoderTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/splunk/SplunkIntegrationInsecureSchemeTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/splunk/SplunkIntegrationInvalidUrlTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/splunk/SplunkIntegrationNormalTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/splunk/SplunkIntegrationTrustAllTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/splunk/package-info.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/testhelpers/CloudEventTestHelper.java, splunk-quarkus/src/test/resources/application.properties
Adds tests for the Splunk Integration.
=> [RHCLOUD-24838] feature tests splunk integration

splunk-quarkus/src/test/java/com/redhat/console/integrations/servicenow/ServiceNowIntegrationTest.java, splunk-quarkus/src/test/java/com/redhat/console/integrations/servicenow/ServiceNowOverrides.java
Adds a few tests to the Service Now integration.
=> [RHCLOUD-24837] feature: test servicenow integration

splunk-quarkus/src/main/java/com/redhat/console/integrations/MainRoutes.java
The integration between notifications-engine and this repo is changing in stage. This PR will help debug an issue in that environment.
=> Log received payload before decoding

splunk-quarkus/src/main/java/com/redhat/console/integrations/CloudEventDecoder.java, splunk-quarkus/src/main/java/com/redhat/console/integrations/splunk/MigrationFilter.java, splunk-quarkus/src/main/java/com/redhat/console/integrations/splunk/SplunkIntegration.java
See https://github.com/RedHatInsights/notifications-backend/pull/2066 for details about the change introduced in this PR.
=> RHCLOUD-27092 Prevent duplicate Kafka processing for Splunk
