- splunk-quarkus/pom.xml
By adding this, we are going to have default metrics path exposed at `/q/metrics`
> [EVNT-195] Add micrometer to pom.xml

- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
- splunk-quarkus/src/main/resources/application.properties
Sets groupId instead of groupInstanceId which is intented for individual
instances within a group.
Fixes the error:
```
Error registering AppInfo mbean: javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=consumer-...
```
Note, that setting the group id is required for the multi-pod/instance deployments.
EVNT-226
> fix(Kafka): set groupId

- .gitignore
- splunk-quarkus/pom.xml
This PR adds Micrometer metrics with the default metrics exposed at `http://host:port/q/metrics` with the following metrics:
```
jvm_memory_used_bytes{area="heap",id="G1 Survivor Space",} 6291456.0
jvm_memory_used_bytes{area="heap",id="G1 Old Gen",} 3.2486912E8
jvm_memory_used_bytes{area="nonheap",id="Metaspace",} 7.7080408E7
jvm_memory_used_bytes{area="nonheap",id="CodeHeap 'non-nmethods'",} 1406336.0
jvm_memory_used_bytes{area="heap",id="G1 Eden Space",} 1.32120576E8
jvm_memory_used_bytes{area="nonheap",id="Compressed Class Space",} 9795632.0
jvm_memory_used_bytes{area="nonheap",id="CodeHeap 'non-profiled nmethods'",} 1.511424E7
CamelExchangesFailed_total{camelContext="redhat-splunk-quarkus",routeId="route3",serviceName="MicrometerRoutePolicyService",} 0.0 …
```
> [EVNT-234] Add Camel microprofile metrics and remove micrometer

- splunk-quarkus/pom.xml
- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/EventAppender.java
- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/EventPicker.java
- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
https://issues.redhat.com/browse/EVNT-44
This PR splits the `events` from the message into their own messages and then sends them to splunk as concatenated json strings (splunk accepts these and recognizes them correctly as separate messages).
It maintains current message schema as it leaves the `events` array in place with only one event per message now.
> [EVNT-44] Split the message by events

- splunk-quarkus/Dockerfile.jvm
- splunk-quarkus/clowdapp.yaml
For example for occasional debugging.
We can later add this for the HTTP issues:
```
-Dquarkus.log.category.\"org.apache.http.impl.conn\".level=DEBUG
```
EVNT-431, EVNT-315
> feat(clowder): parmetrize JAVA_OPTIONS

- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Set logger name to `com.redhat.console.integration.splunk` for messages coming from Log EIP.
The debug logging can be enabled using:
```
-Dquarkus.log.category.\"com.redhat.console.integration.splunk\".level=DEBUG
```
Adds stacktrace debug logging for IOExecptions.
EVNT-432
> feat(log): debug logging and stacktrace for IOException

- grafana/grafana-dashboard-insights-eventing-general.configmap.yaml
Apologies for lack of preview. I'm unable to import the dashboard from the JSON config.
It adds these counters:
* Processed Events
* Handled Events
* Pod Restarts
It adds these time-series charts:
* Events handling rate
* Kafka consumer lag
* CPU consumed
* Average memory consumed
* Containers restarts
* Transmit Bandwidth per pod
Please note that this is an initial dashboard, and I plan to improve it right after publishing it.
EVNT-259
> feat(observability): create first Grafana dashboard

- grafana/grafana-dashboard-insights-eventing-general.configmap.yaml
Fixes and adds couple of more counters.
Value counters (set as Instant vectors):
* Handled Events
* `sum(increase(CamelExchangeEventNotifier_seconds_count{namespace=~"eventing-.+",endpointName="direct://handler",eventType="ExchangeSentEvent"}[$__range]))`
* Successful Events
* `sum(increase(CamelExchangeEventNotifier_seconds_count{namespace=~"eventing-.+",endpointName="direct://success",eventType="ExchangeSentEvent"}[$__range]))`
* Success Rate
* `sum(increase(CamelExchangeEventNotifier_seconds_count{namespace=~"eventing-.+",endpointName="direct://success",eventType="ExchangeSentEvent"}[$__range]))/sum(increase(CamelExchangeEventNotifier_seconds_count{namespace=~"eventing-.+",endpointName="direct://handler",eventType="ExchangeSentEvent"}[$__range]))`
* HTTP Failures
* …
> feat(observability): improve Grafana dashboard

- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Adds `.routeId()` to all routes for the purpose of tracking and metrics.
Example of metrics:
```
CamelExchangesSucceeded_total{camelContext="redhat-splunk-quarkus",routeId="success",serviceName="MicrometerRoutePolicyService",} 0.0
CamelExchangesSucceeded_total{camelContext="redhat-splunk-quarkus",routeId="httpFailed",serviceName="MicrometerRoutePolicyService",} 0.0
CamelExchangesSucceeded_total{camelContext="redhat-splunk-quarkus",routeId="ioFailed",serviceName="MicrometerRoutePolicyService",} 1.0
CamelExchangesSucceeded_total{camelContext="redhat-splunk-quarkus",routeId="return",serviceName="MicrometerRoutePolicyService",} 1.0
CamelExchangesSucceeded_total{camelContext="redhat-splunk-quarkus",routeId="handler",serviceName="MicrometerRoutePolicyService",} 1.0 …
```
> feat: named routes

- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/CloudEventDecoder.java
- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
* Sets `accountId` header out of CloudEvent body.
* Improves logging messages for success and failures.
* Sets verbose messages to be on DEBUG log level.
Example:
```
2022-05-25 13:03:11,750 ERROR [com.red.con.int.splunk] (Camel (redhat-splunk-quarkus) thread #2 - Aggregator) IOFailure for event 9dc9a4b1-8868-4afc-a69d-e8723b20452c (account 12345) to http://localhost:1500: Connect to localhost:1500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
2022-05-25 13:03:45,163 ERROR [com.red.con.int.splunk] (Camel (redhat-splunk-quarkus) thread #2 - Aggregator) HTTPFailure for event 9dc9a4b1-8868-4afc-a69d-e8723b20452c (account 12345) to http://localhost:8088: 403 Forbidden: HTTP operation failed invoking …
```
> [EVNT-438] feat: improved logging

- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
Only passes `Authorization` header to HTTP POST requests. Everything else is filtered out.
Diff:
```diff
POST /services/collector/event HTTP/1.1
Authorization: Splunk TOKENTOKEN
-Ce-id: 9dc9a4b1-8868-4afc-a69d-e8723b20452c
-Ce-rh-account: 12345
-Ce-source: notifications
-Ce-specversion: 1.0
-Ce-time: 2022-02-02T14:09:55.532551Z
-Ce-type: com.redhat.console.notification.toCamel.splunk
-kafka.OFFSET: 8
-kafka.PARTITION: 0
-kafka.TIMESTAMP: 1653407064890
-kafka.TOPIC: platform.notifications.tocamel
-metadata: [url=URLURL, X-Insight-Token=TOKENTOKEN, extras={}]
-targetUrl: URLURL
-timeIn: 1653407056499
```
EVNT-439
> fix(exchange): filter out message headers for HTTP

- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkTrustAllCACerts.java
[EVNT-425](https://issues.redhat.com/browse/EVNT-425)
Now, we verify the if `Enable SSL verification` is selected in Integrations, and route the HTTPS requests based on `trustAll` field in metadata.
Test cases:
1) Have HEC SSL `enabled` in Splunk 
a) Send an HTTPS request with `trustAll` as `true`. You should see a success call.
b) Send an HTTPS request with `trustAll` as `false`. It should fail, as we do not have a certificate properly set.
2)  Have HEC SSL `disabled` in Splunk
a) Send an HTTPS request with `trustAll` as `true`. You should see: `Failed cloud event, id 9dc9a4b1-8868-4afc-a69d-e8723b20452c, with IO exception : Unsupported or unrecognized SSL message`.
b) Send an HTTP request with `trustAll` as `true` or `false`. You should see a success call.
> [EVNT-425] - Integration should accept all CA certs when trustAll is true

- splunk-quarkus/devel.json
- splunk-quarkus/pom.xml
Adds in [quarkus-logging-cloudwatch](https://github.com/quarkiverse/quarkus-logging-cloudwatch) extension witch is being configured by Clowder (via clowder-quarkus-config-source).
Also updates the [clowder-quarkus-config-source](https://github.com/RedHatInsights/clowder-quarkus-config-source) to latest version 1.0.0.
Unfortunately we can safely test this only on stage environment.
EVNT-171
> [EVNT-171] feat: cloudwatch logging

- splunk-quarkus/clowdapp.yaml
Cloudwatch needs log-streams per instance that pushes the logs.  This
fixes it by setting the log-stream via env var to pod's hostname.
EVNT-171
> fix(logging): different log-stream per pod

- splunk-quarkus/pom.xml
- splunk-quarkus/src/main/java/com/redhat/console/notifications/splunkintegration/SplunkIntegration.java
- splunk-quarkus/src/main/resources/application.properties
**Depends on https://github.com/RedHatInsights/clowder-quarkus-config-source/pull/96**
Updates `clowder-quarkus-config-source` dependency to leverage autoconfiguration of Kafka component.
The autoconfiguation is enabled by setting props to `application.properties`. Camel Kafka default values are set. Official values are populated by the library from Clowder config in the initialization.
This autoconfigures:
* brokers
* security protocol
* SASL authentication
* certificates
EVNT-557
> feat(kafka): autoconfiguration with security and authentication

- build_deploy.sh
- pr_check.sh
Copies out the `pr_check.sh` and `build_deploy.sh` scripts to root and changes them to use new common Quay.io repository.
EVNT-613
> chore(ci): reorganize pr_check and delpoy scripts for new repo

- splunk-quarkus/src/main/resources/application.properties
This fixes case when `cacert` is not provided from Clowder config in
case of SSL Kafka connection.
EVNT-668
> fix(kafka): SSL connection w/o pinned CA

- .github/workflows/checkimage.yaml
Creates a daily automation that tracks base image digest and package list digest.
Once there is a change in either in base image or in installed packages, the automation create a pull request with new digest(s). Merging such PR would trigger a new image build.
EVNT-669
> ci: rebuild image on package updates

- build_deploy.sh
This is to ensure that rebuilds always pull new image base and install new packages.
> ci(build): do not use cache for image build

- .github/dependabot.yml
This PR introduces [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) to make sure all Maven dependencies as well as GitHub actions are always up-to-date.
> chore: Introduce dependabot

- splunk-quarkus/src/main/resources/application.properties
Reduces Kafka poll() records to 30 and sets http connection timeout.
This should improve resiliency when there is a higher kafka backlog, to
prevent the consumer being kicked out due to inactivity (timeouted poll).
EVNT-789
> feat improve backlog resiliency

- README.md
- splunk-quarkus/pom.xml
Fix Splunk/SNOW integration switching (using
`camel.main.javaRoutesIncludePattern`) by downgrading Quarkus platform to 2.11.3.Final.
`javaRoutesIncludePattern` property from CLI is was broken in camel-quarkus starting with versions 2.12.0.
References:
* https://camel.apache.org/camel-quarkus/2.16.x/index.html
* https://github.com/apache/camel-quarkus/compare/2.11.0..2.12.0
* https://github.com/apache/camel-quarkus/commit/7d0e3808ffbf4c0e48655f0ac4a041050c24abc4
EVNT-815
> fix: route switching w/ downgrade

- splunk-quarkus/src/main/resources/application.properties
Force to use a sync Kafka commit after each message. Otherwise the auto-commit is done by Kafka lib in a set interval (default 5s).
https://camel.apache.org/manual/camel-3x-upgrade-guide-3_17.html#_camel_kafka
EVNT-820
> fix(kafka): sync manual commit

- splunk-quarkus/src/main/resources/application.properties
Adds 3 retries for Kafka producer with back-off 200ms.
Sets RECONNECT on pollError for Kafka consumer.
https://camel.apache.org/components/3.18.x/kafka-component.html
RHCLOUD-24050
> feat(kafka): retry produce and reconnect consumer

- splunk-quarkus/src/main/java/com/redhat/console/integrations/CloudEventDecoder.java
- splunk-quarkus/src/test/java/com/redhat/console/integrations/CloudEventDecoderTest.java
- splunk-quarkus/src/test/java/com/redhat/console/integrations/testhelpers/CloudEventTestHelper.java
Probably due to an unintended mistake, the Notifications Engine sends the "data"'s JSON as a quoted string, instead as a JSON object itself. Our console.redhat.com CloudEvents specification, which in turn adheres to the Cloud Events specification, defines the "data" key as a JSON object[1], and therefore here we attempt to parse it as it is defined in the specification. However, a fallback of the original parsing way is left too, in order to avoid breaking the integration until the bug is fixed in the Notifications Engine. More information about this can be found in the RHCLOUD-24986[2] Jira ticket.
[1]: https://github.com/RedHatInsights/event-schemas/blob/4119fc6e3820c6519f8f87abc27cdb4604a80db0/schemas/events/v1/events.json#L58-L59
[2]: https://issues.redhat.com/browse/RHCLOUD-24986
> [RHCLOUD-24986] refactor: support deserializing incoming "data" JSON objects

- .gitignore
- splunk-quarkus/src/main/java/com/redhat/console/integrations/servicenow/ServiceNowIntegration.java
- splunk-quarkus/src/main/java/com/redhat/console/integrations/splunk/SplunkIntegration.java
[TargetUrlValidator forbids calls to Splunk using the HTTP scheme.](https://github.com/RedHatInsights/eventing-integrations/blob/88d87dd164b8f46a7caa924a45cf625980a5eaf7/splunk-quarkus/src/main/java/com/redhat/console/integrations/TargetUrlValidator.java#L21-L22)
Therefore, we don't need the code that performs that kind of HTTP calls.
> RHCLOUD-25591 Remove unused HTTP calls to Splunk

- pr_check.sh
This stopped being needed after the Policies rewriting last year.
> Remove policies-engine resources requirement from PR check

- splunk-quarkus/src/main/java/com/redhat/console/integrations/CloudEventDecoder.java
- splunk-quarkus/src/main/java/com/redhat/console/integrations/MigrationFilter.java
- splunk-quarkus/src/main/java/com/redhat/console/integrations/servicenow/ServiceNowIntegration.java
- splunk-quarkus/src/main/java/com/redhat/console/integrations/splunk/SplunkIntegration.java
Related to https://github.com/RedHatInsights/notifications-backend/pull/2065.
`MigrationFilter` is used to switch between the Eventing apps and the Notifications connectors for Splunk and ServiceNow.
> RHCLOUD-26617 Use MigrationFilter with ServiceNow
